{
 "title": "ProSuite User Feedback Analysis",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Number of Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(kcmq.id) AS Correct_Response_Count  from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\n"
    }
   ]
  },
  {
   "title": "Correct Reply Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(kcmq.id) AS Correct_Response_Count  from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\nand LENGTH(kcma.message) != 0 and (score != 1 or score is null )"
    },
    {
     "rawSql": "select COUNT(kcmq.id) AS Abnormal_Responses_Count  from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\nand (LENGTH(kcma.message) = 0 or kcma.message is NULL)"
    }
   ]
  },
  {
   "title": "🖥️ Usage Rate of vLLM Microservices",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vllm_loading\")\r\n  |> filter(fn: (r) => r[\"serviceId\"] == \"MS_ConnetToAPI\")\r\n  |> group(columns: [\"serviceId\"], mode: \"by\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n  |> rename(columns: {_value: \"MS_ConnetToAPI\"})\r\n"
    },
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vllm_loading\")\r\n  |> filter(fn: (r) => r[\"serviceId\"] == \"MS_ConnetToAPI_JIRA\")\r\n  |> group(columns: [\"serviceId\"], mode: \"by\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n  |> rename(columns: {_value: \"MS_ConnetToAPI_JIRA\"})\r\n"
    },
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vllm_loading\")\r\n  |> filter(fn: (r) => r[\"serviceId\"] == \"MS_DocGen_PPT\")\r\n  |> group(columns: [\"serviceId\"], mode: \"by\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n  |> rename(columns: {_value: \"MS_DocGen_PPT\"})\r\n"
    },
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vllm_loading\")\r\n  |> filter(fn: (r) => r[\"serviceId\"] == \"MS_DocGen_WORD\")\r\n  |> group(columns: [\"serviceId\"], mode: \"by\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n  |> rename(columns: {_value: \"MS_DocGen_WORD\"})\r\n"
    },
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vllm_loading\")\r\n  |> filter(fn: (r) => r[\"serviceId\"] == \"MS_DocumentAnalysis\")\r\n  |> group(columns: [\"serviceId\"], mode: \"by\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n  |> rename(columns: {_value: \"MS_DocumentAnalysis\"})\r\n"
    },
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vllm_loading\")\r\n  |> filter(fn: (r) => r[\"serviceId\"] == \"MS_TextToSQL\")\r\n  |> group(columns: [\"serviceId\"], mode: \"by\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n  |> rename(columns: {_value: \"MS_TextToSQL\"})\r\n"
    },
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vllm_loading\")\r\n  |> filter(fn: (r) => r[\"serviceId\"] == \"MS_VoiceToText\")\r\n  |> group(columns: [\"serviceId\"], mode: \"by\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n  |> rename(columns: {_value: \"MS_VoiceToText\"})\r\n"
    }
   ]
  },
  {
   "title": "Number of Feedbacks",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(kcmq.id) as no_feedback from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\nand kcma.score is NULL"
    },
    {
     "rawSql": "select COUNT(kcmq.id) as likes from km_chat_message_question kcmq\r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\nand kcma.score = 5"
    },
    {
     "rawSql": "select COUNT(kcmq.id) as dislike from km_chat_message_question kcmq\r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\nand kcma.score = 1"
    }
   ]
  },
  {
   "title": "👤 Number of Active Users",
   "type": "timeseries",
   "description": "DAU : Daily Active Users  \n\nWAU : Weekly Active Users \n\nMAU : Monthly Active Users ",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "select COUNT(distinct(kcrg.create_user)) as DAU, date_trunc('day',  kcmq.create_time) AS day_range from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  (now() - interval'30 days') AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= now() AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\ngroup by day_range\r\nORDER BY day_range"
    },
    {
     "rawSql": "select COUNT(distinct(kcrg.create_user)) as WAU, date_trunc('week',  kcmq.create_time) AS week_range from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  (now() - interval'30 days') AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= now() AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\ngroup by week_range\r\nORDER BY week_range"
    },
    {
     "rawSql": "select COUNT(distinct(kcrg.create_user)) as MAU, date_trunc('month',  kcmq.create_time) AS month_range from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  (now() - interval'30 days') AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= now() AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\ngroup by month_range\r\nORDER BY month_range"
    }
   ]
  },
  {
   "title": "📊 Active Users & AI Assistant Request Handling Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 17 },
   "targets": [
    {
     "rawSql": "select COUNT(kcmq.id) as Issue_Handle_Count, TO_TIMESTAMP(TO_CHAR(kcmq.create_time - INTERVAL '8 hours', 'YYYY-MM-DD HH24:00:00'), 'YYYY-MM-DD HH24:MI:SS') AS HOUR from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\ngroup by TO_TIMESTAMP(TO_CHAR(kcmq.create_time - INTERVAL '8 hours', 'YYYY-MM-DD HH24:00:00'), 'YYYY-MM-DD HH24:MI:SS')\r\nORDER BY HOUR"
    },
    {
     "rawSql": "select COUNT(distinct(kcrg.create_user)) as Active_Users, TO_TIMESTAMP(TO_CHAR(kcmq.create_time-INTERVAL '8 hours' , 'YYYY-MM-DD HH24:00:00'), 'YYYY-MM-DD HH24:MI:SS')  AS HOUR from km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nleft join km_chat_room kcr \r\non kcmq.room_id = kcr.id\r\nleft join km_chat_room_group kcrg \r\non kcr.group_id = kcrg.id \r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcmq.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\ngroup by  TO_TIMESTAMP(TO_CHAR(kcmq.create_time - INTERVAL '8 hours' , 'YYYY-MM-DD HH24:00:00'), 'YYYY-MM-DD HH24:MI:SS')\r\nORDER BY HOUR"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  }
 ]
}